export const ACTION_TYPES = {
  GET_ROOM_LIST_REGULAR: 'GET_ROOM_LIST_REGULAR',
  GET_ROOM_LIST_ACADEMY: 'GET_ROOM_LIST_ACADEMY',

  GET_ROOM_LIST_FOLLOWED_LOAD: 'GET_ROOM_LIST_FOLLOWED_LOAD',
  GET_ROOM_LIST_FOLLOWED_SUCCESS: 'GET_ROOM_LIST_FOLLOWED_SUCCESS',
  GET_ROOM_LIST_FOLLOWED_FAILED: 'GET_ROOM_LIST_FOLLOWED_FAILED',

  GET_ROOM_LIVE_LOAD: 'GET_ROOM_LIVE_LOAD',
  GET_ROOM_LIVE_SUCCESS: 'GET_ROOM_LIVE_SUCCESS',
  GET_ROOM_LIVE_FAILED: 'GET_ROOM_LIVE_FAILED',

  GET_ROOM_DETAIL_LOAD: 'GET_ROOM_DETAIL_LOAD',
  GET_ROOM_DETAIL_SUCCESS: 'GET_ROOM_DETAIL_SUCCESS',
  GET_ROOM_DETAIL_FAILED: 'GET_ROOM_DETAIL_FAILED',
  CLEAR_ROOM_DETAIL: 'CLEAR_ROOM_DETAIL',
};
