export const ACTION_TYPES = {
  GET_ROOM_LIST_REGULAR: 'GET_ROOM_LIST_REGULAR',
  GET_ROOM_LIST_ACADEMY: 'GET_ROOM_LIST_ACADEMY',

  GET_ROOM_LIVE_LOAD: 'GET_ROOM_LIVE_LOAD',
  GET_ROOM_LIVE_SUCCESS: 'GET_ROOM_LIVE_SUCCESS',
  GET_ROOM_LIVE_FAILED: 'GET_ROOM_LIVE_FAILED',

  GET_ROOM_DETAIL_LOAD: 'GET_ROOM_DETAIL_LOAD',
  GET_ROOM_DETAIL_SUCCESS: 'GET_ROOM_DETAIL_SUCCESS',
  GET_ROOM_DETAIL_FAILED: 'GET_ROOM_DETAIL_FAILED',
  CLEAR_ROOM_DETAIL: 'CLEAR_ROOM_DETAIL',

  GET_ALL_STARS_LOAD: 'GET_ALL_STARS_LOAD',
  GET_ALL_STARS_SUCCESS: 'GET_ALL_STARS_SUCCESS',
  SEND_STAR: 'SEND_STAR',
  SEND_ALL_STARS: 'SEND_ALL_STARS',
};
